---
title: "Exploratory Data Analysis of The UN Vote"
author: "Partha S Satpathy"
date: "March 23, 2017"
output: html_document
---

##Set up the libraries
```{r setup, include=TRUE}
library(ggplot2)
library(dplyr)
library(countrycode)
```

```{r read}
##Read the data from github
x <- read.delim("https://github.com/datasciencelabs/data/raw/master/rawvotingdata13.tab")

##To view the data frame in a better format and save it as votes
votes <- tbl_df(x)
##UN Resolutions desc
desc <- read.csv("C:/Users/parth/Desktop/RProjects/EDA-UN_VOTE/desc.csv", stringsAsFactors=FALSE)

descriptions <- tbl_df(desc)
colnames(descriptions)[1] <- "rcid"
```

```{r use dplyr}
##Pipe Operator- x %>% f(,y) tells you to pass the variable before the operator to the fuction f(x,y)
##It helps you chain a series of command together

##Deplyr verbs
##Filter() -> subsets the observation
##mutate() -> adds a new variable or modifies existing one

votes %>% filter(vote <= 3)
votes %>% mutate(year=session+1945)

##Combine the above 2 functions using pipe
votes %>%
  filter(vote <= 3) %>%
  mutate(year=session+1945)

# Convert country code 100
countrycode(100,"cown","country.name")

# Add a country column within the mutate: votes_processed
votes_processed <- votes %>%
  filter(vote <= 3) %>%
  mutate(year = session + 1945,country=countrycode(ccode,"cown","country.name"))

##summrize() turns many rows into one
votes_processed %>% summarize(total=n()) ##show the no of rowa

votes_processed %>%
  summarize(total=n(),percent_yes = mean(vote == 1))
##The above will fist compare if vote==1, it will consider true as 1 and false as 0,
##It will then calculate the mean. So finally it will give the percentages of yes

##summarize considers the whole group, but if we want to summarize at sub group levels
##we will use group_by
##Below code is to see no of votes and percentage of Yes for every year
##We will group the data set in years before summarizing
votes_processed %>%
  group_by(year) %>%
  summarize(total=n(),percent_yes = mean(vote == 1))

# Summarize by country: by_country
by_country <-
  votes_processed %>%
  group_by(country) %>%
  summarize(total = n(),
            percent_yes = mean(vote == 1))

##arrange() sorts a table based on a variable
by_country %>% 
  arrange(percent_yes)

# Now sort in descending order
by_country %>%
  arrange(desc(percent_yes))

# Filter out countries with fewer than 100 votes
by_country %>%
  filter(total>100) %>%
  arrange(percent_yes)

```

## Analysis using ggplots

```{r Visualizing by Year, echo=TRUE}
#########Visualizing by Year######################
by_year <- votes_processed %>% 
  group_by(year) %>% 
  summarize(total=n(),
            percent_yes=mean(vote==1))
##ggplot has 3 important parts to it
ggplot(by_year, #1. Data Set
       aes(x = year, y = percent_yes)) + #2. X and Y axis
       geom_line() #3. Layer - (type of) graph on the XY-plane

# Change to scatter plot and add smoothing curve
ggplot(by_year, aes(year, percent_yes)) +
  geom_point() +
  geom_smooth()

#########Visualizing by Year and Country######################

##Select the yearly data only for USA
by_year_country_USA <-
  votes_processed %>%
  group_by(year,country) %>% ##Here grou by on both year and country
  summarize(total=n(),percent_yes=mean(vote==1)) %>%
  filter(country == "United States of America")

##Select the yearly data only for USA and France
by_year_country_USA_France <-
  votes_processed %>%
  group_by(year,country) %>% ##Here grou by on both year and country
  summarize(total=n(),percent_yes=mean(vote==1)) %>%
  filter(country %in% c("United States of America","France")) ##Check the %in% for multiple selection

##Compare the US and Farnce data over the years
##For this we can distinguish between the two countries using color aesthetic
ggplot(by_year_country_USA_France,
       aes(x=year,y=percent_yes,color=country)) + geom_line()
       
# Start with by_year_country dataset
by_year_country <- votes_processed %>%
  group_by(year, country) %>%
  summarize(total = n(),
            percent_yes = mean(vote == 1))

# Print by_year_country
by_year_country

# Create a filtered version: UK_by_year
UK_by_year <-
  by_year_country %>%
  filter(country=="United Kingdom of Great Britain and Northern Ireland")

# Line plot of percent_yes over time for UK only
ggplot(UK_by_year, aes(year,percent_yes)) + geom_line()

# Vector of four countries to examine
countries <- c("United States of America",
               "United Kingdom of Great Britain and Northern Ireland",
               "France", "India")

# Filter by_year_country: filterebd_4_countries
filtered_4_countries <-
  by_year_country %>%
  filter(country %in% countries)

# Line plot of % yes in four countries
ggplot(filtered_4_countries, aes(year,percent_yes,color=country))+geom_line()

############Faceting##################
##Plotting all the countries in a single graph is not that intuitive
##So we can plot the graphs individually
##This can be acheived using faceting

# Vector of four countries to examine
countries <- c("United States of America",
               "United Kingdom of Great Britain and Northern Ireland",
               "France", "Japan", "Brazil", "India","Afghanistan","Algeria","Germany")

# Filter by_year_country: filterebd_4_countries
filtered_4_countries <-
  by_year_country %>%
  filter(country %in% countries)
ggplot(filtered_4_countries,
       aes(year,percent_yes)) + geom_line() + facet_wrap(~country)
##But in the above case the Y-axis is standardized
## To make the Y-axis independent, we will use scales parameter of facet
ggplot(filtered_4_countries,
       aes(year,percent_yes)) + geom_line() + facet_wrap(~country, scales = "free_y")
```
##Using Linear Models on the data
```{r model}
# Percentage of yes votes from the US by year: US_by_year
US_by_year <- by_year_country %>%
  filter(country == "United States of America")

# Print the US_by_year data
US_by_year

# Perform a linear regression of percent_yes by year: US_fit
US_fit <- lm(percent_yes ~ year,US_by_year)

# Perform summary() on the US_fit object
summary(US_fit)

#############Tidying a lin regression model##########
##use the tidy() function in the broom package to turn that model into a tidy data frame.

# Load the broom package
library(broom)

# Call the tidy() function on the US_fit object
tidy(US_fit)

##One important advantage of changing models to tidied data frames is that they can be combined.

# Fit model for the United Kingdom
UK_by_year <- by_year_country %>%
  filter(country == "United Kingdom of Great Britain and Northern Ireland")
UK_fit <- lm(percent_yes ~ year, UK_by_year)

# Create US_tidied and UK_tidied
US_tidied <- tidy(US_fit)
UK_tidied <- tidy(UK_fit)

# Combine the two tidied models
bind_rows(US_tidied,UK_tidied)

###############Nesting a Data Frame############################
##Right now, the by_year_country data frame has one row per country-vote pair. 
##So that you can model each country individually, we're going to "nest" all columns besides country, 
#which will result in a data frame with one row per country. The data for each individual country will 
##then be stored in a list column called data.

##Save the by_year_country to a new data frame (removes earlier grouping by year)
by_year_country <- tbl_df(by_year_country)
# Load the tidyr package
library(tidyr)
# Nest all columns besides country
by_year_country %>%
  nest(-country)

##This "nested" data has an interesting structure. The second column, data, is a list, 
##a type of R object that allows complicated objects to be stored within each row. 
##This is because each item of the data column is itself a data frame.

# All countries are nested besides country
nested <- by_year_country %>%
  nest(-country)

# Print the nested data for Brazil
nested$data[[7]]

##The opposite of the nest() operation is the unnest() operation. 
##This takes each of the data frames in the list column and brings those rows back to the main data frame.
# Unnest the data column to return it to its original form
nested %>%
  unnest(data)

#################Tidying several models###################
##The map() function from purrr works by applying a formula to each item in a list.

# Load tidyr and purrr
library(tidyr)
library(purrr)
library(dplyr)
library(broom)
# Perform a linear regression on each item in the data column
by_year_country %>%
  nest(-country) %>%
  mutate(model = map(data,~lm(percent_yes~year,data=.)))

# Add another mutate that applies tidy() to each model
by_year_country %>%
  nest(-country) %>%
  mutate(model = map(data, ~ lm(percent_yes ~ year, data = .))) %>%
  mutate(tidied = map(data,~tidy(lm(percent_yes~year,data=.))))


# Add one more step that unnests the tidied column
country_coefficients <-
  by_year_country %>%
  nest(-country) %>%
  mutate(model = map(data, ~ lm(percent_yes ~ year, data = .)),
         tidied = map(model, tidy)) %>%
  unnest(tidied)

# Print the resulting country_coefficients variable
country_coefficients

################Filtering model elements#######################
# Print the country_coefficients dataset
country_coefficients

# Filter for only the slope terms
country_coefficients %>%
  filter(term == "year")

##Not all slopes are significant, and you can use the p-value to guess which are and which are not.
##However, when you have lots of p-values, like one for each country, you run into the problem of 
##multiple hypothesis testing, where you have to set a stricter threshold. 
##The p.adjust() function is a simple way to correct for this, where p.adjust(p.value) 
##on a vector of p-values returns a set that you can trust.

# Filter for only the slope terms
slope_terms <- country_coefficients %>%
  filter(term == "year")

# Add p.adjusted column, then filter
slope_terms %>%
  mutate(p.adjusted = p.adjust(p.value)) %>%
  filter(p.adjusted < .05)

```

##Join Data Sets and Analyze
```{r Join Data Sets}

# Print the votes_processed dataset
votes_processed

# Print the descriptions dataset
descriptions

# Join them together based on the "rcid" and "session" columns
votes_joined <-
  votes_processed %>%
  inner_join(descriptions,by = c("rcid","session"))

##There are six columns in the descriptions dataset (and therefore in the new joined dataset) 
##that describe the topic of a resolution:
# me: Palestinian conflict
# nu: Nuclear weapons and nuclear material
# di: Arms control and disarmament
# hr: Human rights
# co: Colonialism
# ec: Economic development

# Filter for votes related to colonialism
votes_joined %>%
  filter(co==1)

# Load the ggplot2 package
library(ggplot2)

# Filter, then summarize by year: US_co_by_year
US_co_by_year <- 
  votes_joined %>%
  filter(co==1,country == "United States of America") %>%
  group_by(year) %>%
  summarize(percent_yes = mean(vote==1))

# Graph the % of "yes" votes over time
ggplot(US_co_by_year,
       aes(year,percent_yes)) + geom_line()

##In order to represent the joined vote-topic data in a tidy form so we can analyze and graph by topic, 
##we need to transform the data so that each row has one combination of country-vote-topic. 
##This will change the data from having six columns (me, nu, di, hr, co, ec) to having two columns (topic and has_topic).

# Load the tidyr package
library(tidyr)

# Gather the six mu/nu/di/hr/co/ec columns
votes_joined %>%
  gather(topic,has_topic,me:ec)

# Perform gather again, then filter
votes_gathered <-
  votes_joined %>%
  gather(topic,has_topic,me:ec) %>%
  filter(has_topic == 1)

# Replace the two-letter codes in topic: votes_tidied
votes_tidied <- votes_gathered  %>%
  mutate(topic = recode(topic,
                        me = "Palestinian conflict",
                        nu = "Nuclear weapons and nuclear material",
                        di = "Arms control and disarmament",
                        hr = "Human rights",
                        co = "Colonialism",
                        ec = "Economic development"))

# Print votes_tidied
votes_tidied

# Summarize the percentage "yes" per country-year-topic
by_country_year_topic <-
  votes_tidied %>%
  group_by(country,year,topic) %>%
  summarize(total = n(),percent_yes = mean(vote==1)) %>%
  ungroup(country,year,topic)

# Print by_country_year_topic
by_country_year_topic

# Load the ggplot2 package
library(ggplot2)

# Filter by_country_year_topic for just the US
US_by_country_year_topic <-
  by_country_year_topic %>%
  filter(country=="United States of America")

# Plot % yes over time for the US, faceting by topic
ggplot(US_by_country_year_topic,
       aes(year,percent_yes,color=topic)) + geom_line() + facet_wrap(~topic)


# Load purrr, tidyr, and broom
library(purrr)
library(tidyr)
library(broom)
# Print by_country_year_topic
by_country_year_topic

# Fit model on the by_country_year_topic dataset
country_topic_coefficients <-
  by_country_year_topic %>%
  nest(-country,-topic) %>%
  mutate(model = map(data,~lm(percent_yes~year,data=.)),
         tidied = map(model,tidy)) %>%
  unnest(tidied)

# Print country_topic_coefficients
country_topic_coefficients

##You'll also have to extract only cases that are statistically significant, which means 
##adjusting the p-value for the number of models, and then filtering to include only significant changes.
# Create country_topic_filtered
country_topic_filtered <-
  country_topic_coefficients %>%
  filter(term == "year") %>%
  mutate(p.adjusted = p.adjust(p.value)) %>%
  filter(p.adjusted < .05)
##If we arrange country_topic_filtered on estimate that will give the countries with st slope
##Vanuatu changed its votes mostly on Palestinian conflict
country_topic_filtered %>%
  arrange(estimate)

##Lets check details of Vanuatu
# Create vanuatu_by_country_year_topic
vanuatu_by_country_year_topic <- 
  by_country_year_topic %>%
  filter(country == "Vanuatu")


# Load the ggplot2 package
library(ggplot2)

# Filter by_country_year_topic for just the US
US_by_country_year_topic <-
  by_country_year_topic %>%
  filter(country=="United States of America")


# Plot of percentage "yes" over time, faceted by topic
library(ggplot2)
ggplot(vanuatu_by_country_year_topic,
       aes(year,percent_yes,color=topic)) + geom_line() + facet_wrap(~topic)

```